import { Roboto } from "next/font/google";
import "./globals.css";
import ProtectedRoute from "./protectedRoute/page";
import Footer from "./footer/page";
import { AuthProvider } from "./context/AuthContext";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Europrofil",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} `}>
        <div className="flex flex-col bg-white min-h-screen">
          <AuthProvider>
            <ProtectedRoute>
              <div className="flex-grow">{children}</div>
            </ProtectedRoute>
          </AuthProvider>
          <div className="mt-14">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
